# Copyright (C) 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Test that `.dtsi` and `.h` files may be listed directly in `srcs`."""

load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@rules_devicetree//devicetree:dtb.bzl", "dtb")

dtb(
    name = "srcs_include",
    srcs = [
        "srcs_include.dts",
        "sub/dt-bindings.h",
        "sub/srcs_include.dtsi",
    ],
)

build_test(
    name = "srcs_include_test",
    targets = [
        # keep sorted
        ":srcs_include",
    ],
)
