# Copyright (C) 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Local (host-autodetected) devicetree toolchain."""

load(":constants.bzl", "TOOLCHAIN_TOOLS")

visibility("//devicetree/...")

def _autodetected_toolchain_repo_impl(repository_ctx):
    snippet = ""
    for tool_name in TOOLCHAIN_TOOLS:
        tool_path = repository_ctx.which(tool_name)
        if tool_path:
            repository_ctx.symlink(tool_path, repository_ctx.path(tool_name))
            snippet += """\
    {tool_name} = {repr_tool_name},
""".format(
                tool_name = tool_name,
                repr_tool_name = repr(tool_name),
            )
        else:
            snippet += """\
    {tool_name} = None, # Can't find {tool_name} on host.
""".format(
                tool_name = tool_name,
            )

    build_content = """\
# Generated by devicetree/private/autodetected_toolchain_repo.bzl

load("@rules_devicetree//devicetree/private:toolchain.bzl", "autodetected_devicetree_toolchain")

autodetected_devicetree_toolchain(
    name = "devicetree_toolchain",
{snippet}
    visibility = ["@devicetree_toolchains//:__subpackages__"],
)
""".format(snippet = snippet)
    repository_ctx.file("BUILD.bazel", build_content)
    repository_ctx.file("REPO.bazel", "")

devicetree_autodetected_toolchain_repo = repository_rule(
    doc = """\
Generates a repository containing a `devicetree_toolchain` whose tools are
symlinked from the host's `PATH`. Tools not found on `PATH` are set to `None`
and produce an actionable error only if the toolchain is actually resolved.
""",
    implementation = _autodetected_toolchain_repo_impl,
)
