# Copyright (C) 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Registered devicetree toolchain.

Generates a single `toolchain()` target that resolves to either the hermetic
or the host-local `devicetree_toolchain` depending on
`--@rules_devicetree//devicetree:autodetect_toolchain`. Hermetic is the
default.
"""

visibility("//devicetree/...")

_BUILD_CONTENT = """\
# Generated by @rules_devicetree//devicetree/private/devicetree_toolchains_repo.bzl

config_setting(
    name = "is_autodetecting_toolchain",
    flag_values = {"@rules_devicetree//devicetree:autodetect_toolchain": "1"},
    visibility = ["//visibility:private"],
)

toolchain(
    name = "toolchain",
    toolchain = select({
        ":is_autodetecting_toolchain": "@devicetree_local_toolchain//:devicetree_toolchain",
        "//conditions:default": "@devicetree_hermetic_toolchain//:devicetree_toolchain",
    }),
    toolchain_type = "@rules_devicetree//devicetree:toolchain_type",
    visibility = ["//visibility:private"],
)
"""

def _devicetree_toolchains_repo_impl(repository_ctx):
    repository_ctx.file("BUILD.bazel", _BUILD_CONTENT)
    repository_ctx.file("REPO.bazel", "")

devicetree_toolchains_repo = repository_rule(
    doc = """\
Generates the hub repository holding the single `toolchain()` target
registered by `rules_devicetree`.
""",
    implementation = _devicetree_toolchains_repo_impl,
)
