# Copyright (C) 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Registered devicetree toolchain hub.

Generates a single `toolchain()` target that resolves to the local
`devicetree_toolchain` when
`--@rules_devicetree//devicetree:autodetect_toolchain` is set, and otherwise
registers a fake toolchain against a fake toolchain type so that
user-registered toolchains take precedence during resolution.
"""

visibility("//devicetree/...")

_BUILD_CONTENT = """\
# Generated by devicetree/private/devicetree_toolchains_repo.bzl

load(":fake_toolchain.bzl", "fake_toolchain")

config_setting(
    name = "is_autodetecting_toolchain",
    flag_values = {"@rules_devicetree//devicetree:autodetect_toolchain": "1"},
    visibility = ["//visibility:private"],
)

toolchain_type(
    name = "fake_toolchain_type",
    visibility = ["//visibility:private"],
)

fake_toolchain(
    name = "fake_toolchain",
    visibility = ["//visibility:private"],
)

alias(
    name = "toolchain_type",
    actual = select({
        ":is_autodetecting_toolchain": "@rules_devicetree//devicetree:toolchain_type",
        "//conditions:default": ":fake_toolchain_type",
    }),
    visibility = ["//visibility:private"],
)

toolchain(
    name = "toolchain",
    toolchain = select({
        ":is_autodetecting_toolchain": "@devicetree_local_toolchain//:devicetree_toolchain",
        "//conditions:default": ":fake_toolchain",
    }),
    toolchain_type = ":toolchain_type",
    visibility = ["//visibility:private"],
)
"""

_FAKE_TOOLCHAIN_BZL = """\
visibility("private")

def _fake_toolchain_impl(_ctx):
    return [
        DefaultInfo(),
        platform_common.ToolchainInfo(),
    ]

fake_toolchain = rule(
    implementation = _fake_toolchain_impl,
)
"""

def _devicetree_toolchains_repo_impl(repository_ctx):
    repository_ctx.file("BUILD.bazel", _BUILD_CONTENT)
    repository_ctx.file("fake_toolchain.bzl", _FAKE_TOOLCHAIN_BZL)
    repository_ctx.file("REPO.bazel", "")

devicetree_toolchains_repo = repository_rule(
    doc = """\
Generates the hub repository holding the single `toolchain()` target
registered by `rules_devicetree`.
""",
    implementation = _devicetree_toolchains_repo_impl,
)
