# Copyright (C) 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Hermetic devicetree toolchain from the `dtc` BCR module."""

load(":constants.bzl", "TOOLCHAIN_TOOLS")

visibility("//devicetree/...")

def _hermetic_toolchain_repo_impl(repository_ctx):
    snippet = ""
    for tool_name in TOOLCHAIN_TOOLS:
        snippet += """\
    {tool_name} = {repr_label},
""".format(
            tool_name = tool_name,
            repr_label = repr(str(getattr(repository_ctx.attr, tool_name))),
        )

    build_content = """\
# Generated by devicetree/private/hermetic_toolchain_repo.bzl

load("@rules_devicetree//devicetree/private:toolchain.bzl", "autodetected_devicetree_toolchain")

# `autodetected_devicetree_toolchain` (not `devicetree_toolchain`) is used so
# `DevicetreeToolchainInfo.preprocess` is `None`. This makes preprocessing of
# `*.dts`/`*.dtso` sources opportunistic: it happens when a CC toolchain is
# registered, and is skipped otherwise. Users that need preprocessing to be
# mandatory should register their own `devicetree_toolchain(preprocess = True)`.
autodetected_devicetree_toolchain(
    name = "devicetree_toolchain",
{snippet}
    visibility = ["@devicetree_toolchains//:__subpackages__"],
)
""".format(snippet = snippet)
    repository_ctx.file("BUILD.bazel", build_content)
    repository_ctx.file("REPO.bazel", "")

devicetree_hermetic_toolchain_repo = repository_rule(
    doc = """\
Generates a repository containing a `devicetree_toolchain` that invokes the
tool binaries at the labels passed to this repository rule (typically the
targets exported by the `dtc` BCR module).
""",
    implementation = _hermetic_toolchain_repo_impl,
    attrs = {
        tool_name: attr.label(mandatory = True, doc = doc)
        for tool_name, doc in TOOLCHAIN_TOOLS.items()
    },
)
