# List of `//devicetree:{name}` to be released in docs.
API_DOCS = [
    # keep sorted
    "devicetree_info",
    "devicetree_library",
    "dtb",
    "dtb_composite",
    "dtbo",
    "toolchain",
]

[
    starlark_doc_extract(
        name = "{}.doc_extract".format(doc),
        src = "//devicetree:{}.bzl".format(doc),
        deps = ["//devicetree:{}".format(doc)],
    )
    for doc in API_DOCS
]
